- name: DNS
  hosts: ddns
  become: true
  vars:
    forwarders:
    - 8.8.8.8
    - 8.8.4.4
    key:
      file: "/etc/bind/rndc.key"
      name: "rndc-key"
    zones:
      - name: http.lan
        type: master
        reverse: 10.10.10
        records:
        - name: "@"
          type: NS
          value: "ns1.http.lan."

        - name: "@"
          type: MX
          value: "10 mail.http.lan."

        - name: "ns1"
          type: A
          value: 10.10.10.3

        - name: "ansible.http.lan."
          type: A
          value: 10.10.10.1

        - name: "mail.http.lan."
          type: CNAME
          value: "postfix.http.lan."

        - name: "smtp.http.lan."
          type: CNAME
          value: "postfix.http.lan."

        - name: "pop3.http.lan."
          type: CNAME
          value: "dovecot.http.lan."

        - name: "imap.http.lan."
          type: CNAME
          value: "dovecot.http.lan."

        - name: 1
          type: PTR
          value: "ansible.http.lan."

        - name: 3
          type: PTR
          value: "ns1.http.lan."

        - name: 4
          type: PTR
          value: "ftp.http.lan."

  tasks:
  - name: "Install bind9 to ddns"
    apt:
      name: bind9
      update_cache: true
  - name: "Creating named.conf"
    template:
      src: templates/named.conf.j2
      dest: /etc/bind/named.conf
      owner: root
      group: bind
      mode: 0640
  - name: "Forward for {{ item.name }}"
    template:
      src: templates/db.j2
      dest: "/var/cache/bind/forward.{{ item.name }}.db"
      owner: root
      group: bind
      mode: 0660
    loop: "{{ zones }}"
  - name: "Reverse for {{ item.name }}"
    template:
      src: templates/db.reverse.j2
      dest: "/var/cache/bind/reverse.{{ item.reverse }}.db"
      owner: root
      group: bind
      mode: 0660
    loop: "{{ zones }}"
    when: "item.reverse is defined"
  - name: "Remove database caches"
    file:
      path: "/var/cache/bind/forward.{{ item.name }}.db.jnl"
      state: absent
    loop: "{{ zones  }}"
  - name: "Restarting bind9"
    service:
      name: "bind9"
      state: restarted
- name: DHCP
  hosts: ddns
  become: true
  vars:
    key:
      file: "/etc/bind/rndc.key"
      name: "rndc-key"
    subnets:
    - ip: 10.10.10.0
      netmask: 255.255.255.0
      interface: ens33
      from: 10.10.10.11
      to: 10.10.10.253
      options:
        domain_name_servers:
          - 10.10.10.3
        domain_name: http.lan
        reverse: 10.10.10
  tasks:
  - name: "Installing isc-dhcp-server"
    apt:
      name: isc-dhcp-server
      update_cache: true
  - name: "Creating dhcpd.conf"
    template:
      src: templates/dhcpd.conf.j2
      dest: "/etc/dhcp/dhcpd.conf"
      owner: root
      group: root
      mode: 0644
  - name: "Enabling interfaces"
    template:
      src: templates/dhcp_default.j2
      dest: "/etc/default/isc-dhcp-server"
      owner: root
      group: root
      mode: 0644
  - name: "Restarting the DHCP service"
    service:
      name: isc-dhcp-server
      state: restarted
