- name: "Web"
  hosts: web1
  tasks:
    - name: AD Member
      win_domain_membership:
        dns_domain_name: http.xxx
        hostname: web1
        domain_admin_user: Administrator@http.xxx
        domain_admin_password: Admin123
        state: domain
      register: domain_member
    - name: Reboot
      win_reboot:
      when: domain_member.reboot_required
    - name: Install HTTPS
      win_feature:
        name: Web-Server
        include_sub_features: true
        state: present
    - name: HTTPS Site
      ansible.windows.win_powershell:
        script: |
          New-IISSite -Name "Lola" -PhysicalPath "$env:systemdrive\\inetpub\\testsite" -BindingInformation "*:443" -CertificateThumbPrint "" -CertStoreLocation "Cert:\\LocalMachine\\Webhosting" -Protocol https

