- name: DNS
  hosts: srv1
  become: true
  vars:
    forwarders:
    - 8.8.8.8
    - 8.8.4.4
    key:
      file: "/etc/bind/rndc.key"
      name: "rndc-key"
    #zones:
    #  - name: srv.lan
    #    type: master
    #    reverse: 1.10.10
    #    records:
    #    - name: "@"
    #      type: NS
    #      value: "ns1.srv.lan."
    #    - name: "@"
    #      type: MX
    #      priority: 10
    #      value: "mail.srv.lan."
    #    - name: ns1
    #      type: A
    #      value: 10.10.1.2
    #    - name: control
    #      type: A
    #      value: 10.10.1.1
    #    - name: www
    #      type: A
    #      value: 10.10.1.1
    #    - name: mail
    #      type: A
    #      value: 10.10.1.2
    #    - name: pop3
    #      type: CNAME
    #      value: mail
    #    - name: smtp
    #      type: CNAME
    #      value: mail
    #    - name: imap
    #      type: CNAME
    #      value: mail
    #    - name: 2
    #      type: PTR
    #      value: "ns1.srv.lan."
    #    - name: 1
    #      type: PTR
    #      value: "control.srv.lan."
    #  - name: clt.lan
    #    type: master
    #    reverse: 2.20.10
    #    records:
    #    - name: "@"
    #      type: NS
    #      value: "ns1.clt.lan."
    #    - name: ns1
    #      type: A
    #      value: 10.20.2.2
    #    - name: control
    #      type: A
    #      value: 10.20.2.1
    #    - name: www
    #      type: A
    #      value: 10.20.2.1
    #    - name: mail
    #      type: A
    #      value: 10.20.2.1
    #    - name: pop3
    #      type: CNAME
    #      value: mail
    #    - name: smtp
    #      type: CNAME
    #      value: mail
    #    - name: imap
    #      type: CNAME
    #      value: mail
    #    - name: 2
    #      type: PTR
    #      value: "ns1.clt.lan."
    #    - name: 1
    #      type: PTR
    #      value: "control.clt.lan."
  tasks:
  - name: Setup the DNS zones
    include_tasks: prompt.yaml
    when: zones is undefined
  - name: "Install bind9"
    apt:
      name: bind9
      update_cache: true
  - name: "Create named.conf from template"
    template:
      src: templates/named.conf.j2
      dest: /etc/bind/named.conf
      owner: root
      group: bind
      mode: 0640
  - name: "Create database for the zones"
    template:
      src: templates/db.j2
      dest: "/var/cache/bind/db.{{ item.name }}"
      owner: root
      group: bind
      mode: 0660
    loop: "{{ zones }}"
  - name: "Create reverse databases for the zones"
    template:
      src: templates/db.reverse.j2
      dest: "/var/cache/bind/db.{{ item.reverse }}"
      owner: root
      group: bind
      mode: 0660
    loop: "{{ zones }}"
    when: "item.reverse is defined"
  - name: "Remove database caches"
    file:
      path: "/var/cache/bind/db.{{ item }}.jnl"
      state: absent
    loop: "{{ zones | map(attribute='name') + zones | map(attribute='reverse') }}"
  - name: "Restart bind9 service"
    service:
      name: bind9
      state: restarted
- name: DHCP
  hosts: virtualmachines
  become: true
  vars:
    key:
      file: "/etc/bind/rndc.key"
      name: "rndc-key"
    subnets:
    - ip: 10.10.1.0
      netmask: 255.255.255.0
      interface: ens36
      from: 10.10.1.10
      to: 10.10.1.253
      options:
        domain_name_servers:
        - 10.10.1.1
        domain_name: srv.lan
        reverse: 1.10.10
        routers:
        - 10.10.1.254
    - ip: 10.20.2.0
      netmask: 255.255.255.0
      interface: ens37
      from: 10.20.2.10
      to: 10.20.2.253
      options:
        domain_name_servers:
        - 10.20.2.1
        domain_name: clt.lan
        reverse: 2.20.10
        routers:
        - 10.20.2.254
    fixed_hosts:
      - name: control
        mac: "00:0c:29:44:be:04"
        address: 10.10.1.10
  tasks:
  - name: "Install isc-dhcp-server"
    apt:
      name: isc-dhcp-server
      update_cache: true
  - name: "Create dhcpd.conf"
    template:
      src: templates/dhcpd.conf.j2
      dest: "/etc/dhcp/dhcpd.conf"
      owner: root
      group: root
      mode: 0644
  - name: "Only enable the neccessary interfaces"
    template:
      src: templates/dhcp_default.j2
      dest: /etc/default/isc-dhcp-server
      owner: root
      group: root
      mode: 0644
  - name: "Restart isc-dhcp-server service"
    service:
      name: isc-dhcp-server
      state: restarted