- name: Install AD and CA
  hosts: dc-ca
  tasks:
  - name: Rename
    win_hostname:
      name: DC-CA
  - name: Domain cucc
    win_domain:
      install_dns: true
      dns_domain_name: skill39.net
      safe_mode_password: Admin123
    register: res
  - win_reboot:
    when: res.reboot_required
  - name: Install and configure AD
    win_domain_controller:
      dns_domain_name: skill39.net
      domain_admin_user: Administrator@skill39.net
      domain_admin_password: Admin123
      safe_mode_password: Admin123
      state: domain_controller
      site_name: DC-CA
    register: res
  - win_reboot:
    when: res.reboot_required
  - name: Install CA
    win_feature:
      include_management_tools: true
      name: ADCS-Cert-Authority
  - name: Powershell
    ignore_errors: true
    win_shell: |
      ssh-keygen -t rsa -N '""' -f $env:USERPROFILE\.ssh\id_rsa
  - name: Fetch
    fetch:
      src: C:\Users\Administrator\.ssh\id_rsa.pub
      dest: win_rsa.pub
- name: Copy rsa to Debvpn
  hosts: debvpn
  become: true
  tasks:
  - name: Copy rsa
    copy:
      src: win_rsa.pub/dc-ca/C:/Users/Administrator/.ssh/id_rsa.pub
      dest: /root/.ssh/authorized_keys
- name: Back to Win
  hosts: dc-ca
  become: yes
  become_method: runas
  vars:
    ansible_become_user: SKILL39\Administrator
    ansible_become_password: Admin123
  tasks:
  - name: PS
    win_shell: |
      scp -o "StrictHostKeyChecking no" root@10.10.10.1:ca.crt C:\
      Import-Certificate -FilePath C:\ca.crt -CertStoreLocation "Cert:\LocalMachine\Root"
      scp -o "StrictHostKeyChecking no" root@10.10.10.1:dc-ca.pfx C:\
      Install-AdcsCertificationAuthority -CAType EnterpriseSubordinateCa -CertFile C:\dc-ca.pfx -Force