---
- name: "Setting up rdp1"
  hosts: rdp1
  become: true
  tasks:
  - name: "Become AD member"
    win_domain_membership:
      dns_domain_name: http.xxx
      hostname: web2
      domain_admin_user: Administrator@http.xxx
      domain_admin_password: Admin123
      state: domain
    register: domain_member
  - name: "Rebooting rdp1"
    win_reboot:
    when: domain_member.reboot_required
  - name: "Installing IIS"
    win_feature:
      name: Web-Server
      include_sub_features: true
      state: present