---
- name: CLT_SETUP
  hosts: clt
  gather_facts: false
  tasks:
    - name: Test connection with ping 
      win_ping:

    - name: Become an AD member
      ansible.windows.win_domain_membership:
        dns_domain_name: http.xxx
        hostname: clt
        domain_admin_user: Administrator@http.xxx
        domain_admin_password: Admin123
        state: domain
      register: domain_state

    - ansible.windows.win_reboot:
      when: domain_state.reboot_required

